services:
- type: web
  name: khoji
  env: docker
  rootDir: .
  plan: starter
  runtime: docker
  healthCheckPath: /
  envVars:
    - key: DB_HOST
      sync: false
    - key: DB_PORT
      value: 5432
    - key: DB_NAME
      sync: false
    - key: DB_USER
      sync: false
    - key: DB_PASS
      sync: false
    - key: DB_SSLMODE
      value: require
    - key: SUPABASE_URL
      sync: false
    - key: SUPABASE_SERVICE_ROLE
      sync: false
    - key: SUPABASE_BUCKET
      value: uploads

