<section class="container m-5">
    <p>Please read these Terms & Conditions carefully before using the https://dialworker.com website or Dialworker mobile application operated and managed by SAHAYA GROUP.
Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms and conditions. These Terms and conditions apply to all visitors, users and others who access, download, register and use Dialworker website/application. By accessing, downloading or using the Dialworker website/application you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access website/application.
Intellectual Property Rights
Dialworker.com is owned and managed under copyright act by SAHAYA GROUP. All aspects of Dialworker website and application, such as the designs, transactional flow, look and feel, contents, graphics and images including logo are protected under copyright act. As the law enforces, users are restricted from downloading, reusing, reconfiguring or imitating any of the proprietary material. Any such activity is expressly prohibited without prior permission of Dialworker.com or written consent of owner. If Dialworker.com identifies that any user engaged in such activities; appropriate legal action may be taken, including without limitation civil, criminal and injunctive redress.       
Use of Dialworker Platforms (Web/App)
The Dialworker.com is a common platform for customers and service providers that may contain profiles, email facility, chat facility, blogs, job posting, advertisements and other communication channels to communicate with each other or to avail the services. Hence, users may use these facilities only to send and receive messages that are relevant and appropriate to the intended use. Violation of this term may force Dialworker.com to take appropriate legal action against the user, including without limitation civil, criminal and injunctive redress.            
Customer Information
Dialworker.com, during the new account registration, may ask customer to share the personal information which is required to deliver the service. Dialworker.com assumes customer provides the accurate information about his/her identity, contact information. The given information will be verified during the registration process.  Dialworker.com only makes a sincere attempt to provide best service to its customers and hence does not take full responsibility of suitability, reliability, timeliness, or accuracy of the Services requested and provided by customers. Dialworker.com dos not confirm the identity of customers who they claim to be. If Dialworker finds any information wrong or any malpractice, agreement with customer will be terminated with immediate effect.
Service Provider Information
Dialworker.com performs the background verification of service providers to ensure the safety and security of customers. Dialworker.com enters into Service Level Agreement (SLA) with every service provider during the on-boarding process. This attempt is a sincere effort to ensure the best and effective service to our customers. Dialworker.com does not take full responsibility suitability, reliability, timeliness, or accuracy of the services provided.     
Ad policy: payment or non payment ads are published as per sole discretion of dialworker and for paid ads only after the realization of payment.
Account/Password Protection
Customer is solely responsible for maintaining the confidentiality of password and service account provided by Dialworker.com for accessing the offered service. Customer is solely and fully responsible for all activities that occur under the password or account. Dialworker.com has no control and expressly disclaims any liability derived there from over the use of any customer’s account. If the customer is suspicious about the activities under the account or breach of account, he/she should immediately reach Dialworker.com to block the account. 
Termination of Service
Dialworker.com reserves the right to suspend or terminate your association with us for violation of any of our policies, posted on the website time to time. The termination will be with prior notice via mail and it will be effective immediately after the delivery of notice. Dialworker.com also reserves the right to take legal action, including without limitation pursuing civil, criminal, and injunctive redress, for inappropriate or offensive behavior. Breach or violation of any of the policies will enforce the termination or expiration of the agreement with Dialworker.com. The termination of agreement will also enforce the cancellation of ongoing requested services, refunds and other disputes by the customer. 
Billing and Payment Policy
Dialworker.com offers its customer to pay the service provider either mobile wallet, online using net banking / debit card . Dialworker.com expressly claims no responsibility of refund for payment made by cash. Customer is liable to pay the invoiced amount immediately after the work completion.  Dialworker.com takes no responsibility for money paid to Service Provider with or without our knowledge, we have no control over payments made to Service Provider other than what is agreed between Dialworker and customer. We discourage any tips or reward to any of our Service Provider however if any customer is doing so is completely based on their own will and decision.
If the money gets deducted from the user account and the payment is not reflected in the application in case of ad publication, you are requested to contact the DIALWORKER customer care support at help@dialworker.com. Your payment will be reflected within 48 hours if the transaction is successful at the payment gateway service provider. If your payment status is not updated in the given time frame, please contact the bank for further enquiries, DIALWORKER does not take responsibility on such cases and payment will reflect in your bank account as per Bank's TAT.    
Links to Other Web Sites
Dialworker.com may contain links to third-party websites or services that are not owned or controlled by DIALWORKER. DIALWORKER Services has no control over and assumes no responsibility for, the content, privacy policies, or practices of any third party websites or services. You further acknowledge and agree that DIALWORKER Services shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such websites or services. We strongly advise you to read the terms and conditions and privacy policies of any third-party websites or services that you visit.
Service Delivery
Dialworker.com does not provide or deal with material or spare parts required for delivering the service. Customers are requested to buy the material their own to carry out the service. Service provider is solely responsible/ liable for damages caused during service delivery, in such events customer is requested to first contact the customer support team and then may lodge a complaint against the service provider, if the damage is resolved with mutual understanding.
Customer is requested to report/inform Dialworker.com immediately for any misconduct or unsatisfied behavior of any of our service provider so that we can take necessary action in order to resolve incidents and prevent the occurrence of such incidence in future. However, if the misconduct is falling in the category of breach of law then the customer may deal with that as per the applicable laws directly with the service provider and Dialworker.com will not be responsible in such case. Also, if the service provider involves in any criminal activities during the service delivery or at any stage of service cycle the customer, at its own will can take direct action under the laws of the country and also keep us informed on full details of the same. Dialworker.com will not be party to any such action.
Beauty and Healthcare Services
Dialworker acts as the technology platform to customers to avail the medical services from a specific service provider and therefore not responsible for any damage or negligence caused during service delivery. As a technology infrastructure provider, Dialworker connects the customer with the service provider and offer convenience for online payment facility, on the other side payment assurance to service providers. The Service Icons will have the service provider brand logo in Dialworker’s common Icon theme and it’s strictly customer’s preference to avail the services from a specific service provider.  If the service provider is involved in any criminal activity, exhibits any offending behavior, misconduct or medical negligence at any stage of service cycle, customer can take legal action against service provider under applicable Indian Law, Dialworker will not party to any such action.
Home Appliances & Consumer Electronics
Repair Charges /Visit Charges - is the charges on the technician visit to customer premises - needs to be paid by the customer as per service provider’s policy. Post technician visit - if any spare needs to be changed or replaced would be extra as per current market rates
Governing Law
These Terms shall be governed and construed in accordance with the laws of Country without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.
Dispute Resolution Management
Dialworker.com reserves the right to manage, resolve or decline the disputes with customer. Any disputes raised by customer will be processed by the Dialworker team and notify the customer on acceptance of dispute, via mail along with complaint number.  Dialworker team will enquire the complaint and based on the findings customer will be receiving the response from Dialworker team within 7 working days from the day of complaint. If the customer is not satisfied with the resolution, the parties agree to resolve the matter amicably vide arbitration under the Indian Arbitration & Conciliation Act, 1996. The venue of the arbitration shall be Visakhapatnam, India. The language of the arbitration shall be English.         
 
Changes to the ‘Terms & Conditions’ and Other Policies
Dialworker.com reserves the right, at our sole discretion, to modify, delete or replace the terms and conditions or any other policies at any time, with or without prior notice to the customer. . What constitutes a material change will be determined at our sole discretion. We ensure our sincere effort to bring the changes via mail and application to accept the changes. We request the customers and service providers to visit the policies and terms & conditions at a certain frequency to update the same. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.
Contact Us
If you have any queries regarding our services, please write to us on help@dialworker.com or call our customer support team 
@ DIALWORKER /Dialworker/Policy/Terms & Conditions-Ver 1 Updated as on 05 October, 2021

</p>
</section>